### ISSUE TITLE
2nd Approach according to article and Version Control

### ISSUE THREAD

**Issue by UtsavTrivedi16** [vittali/vittali.ch-8-mcunit-msp432#2]
Hello Peter,

I found your article very insightful for learning. Have you made a tutorial for the second approach?  Also can you make a tutorial for SVN/Git  and CI/CD integration? For large projects, running unit tests before every commit might not be practical and would need a server. Even if you have some insights on this that would be helpful. 

Thanks,

Utsav

**Comment by vittali** [comment]
Hi Utsav
Thanks for your message. Unfortunately, due to time constraints, I haven't been able to finish this tutorial. In particular, the projects requires a couple of Java libraries which I am currently rewriting with the new features of Java 17. It will take a couple of months or so, but I will definitively update this project since I feel the approach is promising. So stay tuned.
Concerning CI: once you can run your tests from the command line with gradle it is really simply. Depending on which tool you use (Github, Bitbuck), you just put a small yaml file in your repo and you activate the CI on the repo server side (travis, ...).
This is one of the reasons why I want to be able to run all my mcu project tests from the command line.

**Comment by UtsavTrivedi16** [comment]
Thanks Travis. Really valuable information. :)
